### ISSUE TITLE
top bar moving 

### ISSUE THREAD

**Issue by bobzer** [niklas-englert/9GAG-Controls#10] opened 2024-08-30 14:22 UTC
Hi,

Thanks for your extension it's very nice, but since I installed it the top bar of 9gag (where there is the profile/search/post 9gag button) move down which hide part of the post under.
At first when the page is loaded it works well then without doing anything just wait a few seconds and the top bar go down, which is very weird : 
![image](https://github.com/user-attachments/assets/924382bd-db2d-4bcd-878a-ec4a9075e627)

have a good day and .. ok here is not 9gag

**Comment by niklas-englert** [comment] 2024-08-30 20:16
Thanks for reporting an issue!

However I cannot reproduce this behavior.  
The screenshot already tells me you running the Chrome version, but could you please provide more details on when this happens. Answering the following questions would help a lot:

1. Am I getting this right: The top bar just pops down after some seconds *without* any scrolling before?
2. Does this happen reliably every time you visit 9GAG? If not: How rare is it or how many seconds does it take (roughly)? 
3. Did you make sure the issue only happens with my extension installed and is definitely not happening without it?
4. Without my extension: Is there an Ad banner popping in above the top bar (this extension might block an ad in a buggy way)? If yes: could you please make a screenshot of the ad?

**Comment by bobzer** [comment] 2024-08-30 21:35
Thanks for taking the time
1. yes 
2. yes almost 100%, (sometime it goes back up)
3. yes sure
4. I think that's a very good point, when I disabled AdblockPlus the bug went away, If I reenable it it come back. Strange part is even abp disabled i don't see an ad on top (and I don't have another kind of adblocker)

here some gif to show you : https://imgur.com/a/tkKN0sC (couldn't post it, I tried to make it lightert but still too big)

**Comment by niklas-englert** [comment] 2024-09-02 07:06
I was able confirm this with 9GAG-Controls & ABP, but also with ABP *without* my extension (only sometimes).  
I was not able to confirm this with just 9GAG-Controls. Also everything seems to be working right with uBlock Origin (in my opinion a better Ad blocking solution).

![image](https://github.com/user-attachments/assets/c61e02fd-732b-447e-8d9b-a35473894b55)
<sup>screenshot of my tests: issue occurs in ABP even without 9GAG-Controls. ABP also doesn't seem to block all ads.</sup>
The main problem seems to be with Adblock Plus. I'll close this issue as unresolved.

**Closed as completed** 2024-09-02 07:07 UTC
Labels: bug, wontfix
